language: python
python:
  - "2.7"
env:
  - LOG=debug

before_install:
  - sudo apt-get -y install python-pip python-dev swig libssl-dev
install:
  - pip install --use-mirrors -r requirements.txt
  - pip install --use-mirrors --allow-external twill -r dev-requirements.txt

before_script:
  - flake8 hivy tests
script:
  - nosetests -w tests --with-coverage --cover-package=hivy

after_success:
  - coveralls

branches:
  only:
    - master
    - develop
