language: python
python:
  - "2.7"
env:
  - LOG=debug

before_install:
  - sudo apt-get -y install python-pip python-dev swig
install:
  - pip install --use-mirrors nose flake8 coveralls
  - pip install --use-mirrors -r requirements.txt

before_script:
  - flake8 intuition tests
script:
  - nosetests -w tests --with-coverage --cover-package=intuition

after_success:
  - coveralls

branches:
  only:
    - master
    - develop
