#! /bin/bash

if [ -z "$NODE_ID" ]; then
  export NODE_ID="$(hostname)"
fi

sed -i 's/#master:/master:/g' /etc/salt/minion
sed -i "s/master:.*$/master: $SALT_MASTER/g" /etc/salt/minion

sed -i 's/#id:/id:/g' /etc/salt/minion
sed -i "s/id:.*$/id: $NODE_ID/g" /etc/salt/minion

/usr/bin/salt-minion -l debug
