#! /usr/bin/env python
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
#
# Copyright (c) 2014 Hive Tech, SAS.


'''Hivy

Usage:
  hivy -h | --help
  hivy --version
  hivy [--bind=<ip>] [--port=<port>] [-d | --debug] [--log <level>]

Options:
  -h --help       Show this screen.
  --version       Show version.
  --debug         Activates Flask debug
  --bind=<ip>     Listens on the given ip [default: 127.0.0.1]
  --port=<port>   Listens on the given port [default: 5000]
  --log=<level>   Log output level [default: debug]
'''


from docopt import docopt
from hivy.app import app, log
from hivy import __version__
import hivy.logger as logger


if __name__ == '__main__':
    args = docopt(__doc__, version='Hivy, Hive api %s'.format(__version__))

    log_setup = logger.setup(level=args['--log'], show_log=args['--debug'])
    with log_setup.applicationbound():
        log.info('server ready',
                 log=args['--log'],
                 debug=args['--debug'],
                 bind='{}:{}'.format(args['--bind'], args['--port']))

        app.run(host=args['--bind'],
                port=int(args['--port']),
                debug=args['--debug'])
