#! /usr/bin/env python
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
#
# Copyright (c) 2014 Hive Tech, SAS.


'''Hivy

Usage:
  hivy -h | --help
  hivy --version
  hivy [--bind=<ip>] [--port=<port>] [-d | --debug]

Options:
  -h --help       Show this screen.
  --version       Show version.
  --debug         Activates Flask debug
  --bind=<ip>     Listens on the given ip [default: 127.0.0.1]
  --port=<port>   Listens on the given port [default: 5000]
'''


from docopt import docopt
import hivy


if __name__ == '__main__':
    args = docopt(__doc__,
                  version='Hivy, Hive api %s'.format(hivy.__version__))

    hivy.app.run(host=args['--bind'],
                 port=int(args['--port']),
                 debug=args['--debug'])
